#!/bin/bash
#SBATCH --mem=120g
#SBATCH -t 24:00:00
#SBATCH -n 32
#SBATCH -p general

module load anaconda
source activate Gilbert-work

index="/work/users/g/g/ggiri/GENOME/Human_ERCC/RSEM/hg38"
fastqdir="/work/users/g/g/ggiri/PCBP1/RIP_C2BBe1/Data"
outdir="/work/users/g/g/ggiri/PCBP1/RIP_C2BBe1/RSEM"
file=$1

rsem-calculate-expression --star \
        --star-path /work/users/g/g/ggiri/Tools/STAR/bin/Linux_x86_64_static/ \
        --num-threads 32 \
        --seed 77 \
        --output-genome-bam \
        ${fastqdir}/${file}.fastq \
        ${index} \
        ${outdir}/${file}
